version: '3.9'
services:
  mysql-master:
    image: bitnami/mysql:latest
    container_name: mysql-master
    restart: unless-stopped
    ports:
      - "3370:3306"
    env_file: config/mysql-master/.env.master
    cap_add:
      - all
    volumes:
      - ./data/mysql-master/data:/bitnami/mysql/data
      - ./config/mysql-master/master.cnf:/opt/bitnami/mysql/conf/my.cnf
    environment:
      - TZ:${TZ}
      - MYSQL_USER:${MYSQL_USER}
      - MYSQL_PASSWORD:${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD:${MYSQL_PASSWORD}
    networks:
      default:
        aliases:
          - mysql

  mysql-slave:
    image: bitnami/mysql:latest
    container_name: mysql-slave
    restart: unless-stopped
    env_file: config/mysql-slave/.env.slave
    ports:
      - "3380:3306"
    cap_add:
      - all
    volumes:
      - ./data/mysql-slave/data:/bitnami/mysql/data
      - ./config/mysql-slave/slave.cnf:/opt/bitnami/mysql/conf/my.cnf
    environment:
      - TZ:${TZ}
      - MYSQL_USER:${MYSQL_USER}
      - MYSQL_PASSWORD:${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD:${MYSQL_ROOT_PASSWORD}
    networks:
      default:
        aliases:
          - mysql
