version: '3'
services:
  mysqlmaster:
    platform: linux/amd64
    image: mysql:8.0.29
    ports:
      - "3336:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - ./data/mysql-master:/var/lib/mysql/
      - ./config/mysql-master:/etc/mysql/conf.d/
  mysqlslave:
    platform: linux/amd64
    image: mysql:8.0.29
    ports:
      - "3337:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - ./data/mysql-slave:/var/lib/mysql/
      - ./config/mysql-slave:/etc/mysql/conf.d/
    depends_on:
      - mysqlmaster
  mysqlconfigure:
    platform: linux/amd64
    image: mysql:8.0.29
    environment:
      - "MYSQL_SLAVE_PASSWORD=root"
      - "MYSQL_MASTER_PASSWORD=root"
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_REPLICATION_USER=repl"
      - "MYSQL_REPLICATION_PASSWORD=repl"
    volumes:
      - ./mysql_connector.sh:/tmp/mysql_connector.sh
    command: /bin/bash -x /tmp/mysql_connector.sh
